### ISSUE TITLE
Extension causes error on magento compile

### ISSUE THREAD

**Issue by satriowinarendro** [meanbee/magento2-webappmanifest#1]
This error is shown on setup:di:compile command execution
**Class Meanbee\WebAppManifest\Block\string does not exist**

Step i take to get the error
- installed the extension via composer successfully without any errors
- trying to fully deploy the site (upgrade,**compile**,deploy)

Am i missing some step or something? Thank you

**Comment by punkstar** [comment]
What version of Magento are you using?

**Comment by satriowinarendro** [comment]
@punkstar Magento 2.1.3

**Comment by tgerulaitis** [comment]
What version of PHP are you running?

This is most likely caused by us using [scalar type declarations](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.scalar-type-declarations) in https://github.com/meanbee/magento2-webappmanifest/blob/master/src/Block/Register.php#L21 meaning this extension is only compatible with PHP 7.0+.

**Comment by satriowinarendro** [comment]
i see that probably is the cause of my problem, my php version is 5.6.24, okay then im closing this issue now, thanks for super fast respond devs, cheers
